### PR TITLE
Update Shrinkwrap to Not Include Dev Dependencies

### PR DESCRIPTION
**Pull request by calebeno**

### CODE REVIEW

**Comment by calebeno** [comment]
I was testing some things out and realized I should definitely not include the dev dependencies in the shrinkwrap file.  Also made a few syntax edits in the test file.  Definitely turn on Travis CI if you get a chance!

**Comment by oe** [comment]
I've made some improvements:
- Enabled travis CI
- Added Eslint(with standard code style, which semicolons are removed)
- improve scripts in package.json

And I also added a new feature to deal with truncating at word boundary(#7) by added an option `keepWords`, test cases are required to complement. 

I'll publish this version to npm after tests are complete, or you can do some help😁

You can check my changes on evecalm/truncate-html@fc19a5833f9f856939f444c4c4abc456819b66e5

I'll keep npm-shrinkwrap.json, it can make sure users installing the extact version the dependences we use which has passed tests. check [What is the difference between npm-shrinkwrap.json and package-lock.json?](https://stackoverflow.com/questions/44258235/what-is-the-difference-between-npm-shrinkwrap-json-and-package-lock-json) for more details


**_So this pull request will be closed._**

**Comment by calebeno** [comment]
Things are looking great!  Thank you so much for taking some time to work on this.  I've never done an npm package before so I forked the code and was working with publishing and pulling it into a project.  If all of the dev dependencies are in the shrinkwrap, I think it automatically tries to install all of the dev dependencies when you bring in the package into a project which is definitely not desirable as the only one we actually need is cheerio.

I checked that link about shrinkwrap vs lock.  The accepted answer suggests using the package-lock file for libraries but I'm ok with using the shrinkwrap.  I do think the dev dependencies need to be taken out fo the shrinkwrap file.

**Comment by oe** [comment]
You may have misunderstood `npm-shrinkwrap.json` and `package-lock.json`, they just make sure users(who use this module) or developers(who contribute this project) will install the exact version that specified in `npm-shrinkwrap.json` and `package-lock.json`, not inaccuracy version in package.json, to avoid (dev)dependencies version's variations(APIs of dependency may changes) causing some unexpected bugs. Users will only install modules specified in **_package.jon's_** `dependencies` fields, none of the devDependencies will be installed. Check [dependencies vs devdependencies vs peerdependencies](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies) for more details

`npm-shrinkwrap.json` has a better compatibility than `package-lock.json`.
`npm v5.0` introduced `package-lock.json` to lock the dependencies' versions, which is stolen from `yarn`.  But `npm v5.0` is really buggy, especially when install some native modules or modules that has `bin` entry in package.json. So I downgrade to `npm v4` to make sure my projects works well. Then I just turn to [yarn](https://yarnpkg.com/) to manage project's dependencies.

**Pull request closed without merging**
