### PR TITLE
Updating Files Available For NPM

### PR DESCRIPTION
**Pull request by calebeno**
Yes, this was a bit confusing but I think I've figured it out.  After playing around with a lot of back and forth settings, I got it working the way I expected it to.  The shrinkwrap just contains the dependencies.  If you include the dev dependencies, anyone who installs it will also install the dev ones as well, which I don't think is desirable.  I also set up the "files" property to include only the dist folder and the shrinkwrap.  Now when someone installs the package they'll just get the dist folder, the readme, and the dependencies.

Also, I removed the postinstall which was running when installing the npm package.  Don't think that's something we want anyone to pick up.

Sorry that there are so many commits in this.  As I said I did a lot of playing around.  Definitely do a squash so all of that doesn't pollute your commit history.

### CODE REVIEW

**Comment by oe** [comment]
You are right about `npm-shrinkwrap.json`, it will make install dev dependencies.
I've verified this by create a `package.json` and run `npm i` in that folder.
```json
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "truncate-html": "git+https://github.com/evecalm/truncate-html.git"
  },
  "author": "",
  "license": "ISC"
}
```


And `postinstall` is not necessary.

Due to so many commits, I will fix it myself, and complete the test cases and readme.

**_So This pull request will be closed._** Thank you again.

**Comment by calebeno** [comment]
Question, is there any way to credit @calebeno instead of @cenoicc?  cenoicc is my work github and I accidentally submitted my first pull request with that one.  I'm actually planning on deleting that account to avoid future confusion.

**Comment by oe** [comment]
I see .I've added @calebeno to `readme.md` and `package.json`. Thanks again :)

**Comment by calebeno** [comment]
Thank you!  This is the first public npm package I've ever contributed to.  It's been a fun experience.  When do you think you'll formally do the 1.0.0 release?

**Comment by oe** [comment]
Maybe in this weekend. I'm still testing it by practicing in real project.

**Comment by calebeno** [comment]
Sorry to ping you again, just curious if you've gotten any closer to a release?  Looking to pull this into my project as soon as you're ready to go.  (Project preference is to pull from npm, not from github directly)

**Pull request closed without merging**
