### PR TITLE
Adding Tests To Show Ellipsis Error

### PR DESCRIPTION
**Pull request by calebeno**
Hello again,

I was doing some testing using this on my application and happened upon an issue.  I wrote some tests in this PR to demonstrate it.  It looks like the crux of it is that the ellipsis is no longer being added if the last character after the truncation is the last character in a tag.  Two of these tests should fail on TravisCI.  Take a look and let me know what you think.

### CODE REVIEW

**Comment by calebeno** [comment]
Found and fixed the issue.  Take a look and let me know what you think.  If it looks good, could you merge and submit a new rc candidate?  I'll run some more tests with my application to see if I run into anything else.

**Review by oe — APPROVED** [review]
AWESOME!

**Comment by oe** [comment]
I've just updated npm to `1.0.0-rc.5`, you may have a try.
I was away from work for my Chinese new year holidays, just returned today.

**Comment by calebeno** [comment]
Happy New Year!  Hope it was a good celebration.  Thanks for the merge and publish.  I'll download it and test it today.  There should be pretty solid test coverage for the individual options.  It might be a good idea to add some tests to cover cases with multiple options selected, just as a suggestion.

**Comment by oe** [comment]
😮  That would be a hard work,  I'll try when got some free time

**Pull request merged**
